version: "3.8"

services:

  mysql:
    container_name: mysql
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 11111111
      MYSQL_DATABASE: fabric8app
    networks:
      fabric8app-service:
    healthcheck:
      test: ["CMD-SHELL", "mysql --user=root --password=11111111 --execute 'show databases;' || exit 1"]
      interval: 15s
      retries: 5

  fabric8app:
    container_name: fabric8app
    depends_on:
      - mysql
    image: vladbogdadocker/fabric8app:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/fabric8app
    ports:
      - "8089:8089" #browser:local
    networks:
      fabric8app-service:
    restart: on-failure

networks:
  fabric8app-service: